### PR TITLE
Create 2023-area63-fall-conference

### PR DESCRIPTION
**Pull request by Area63**
Create 2023 Area 63 Fall Conference event.

### CODE REVIEW

**Comment by MTecknology** [comment]
A file was removed with no reason why. Two more random files were added and not linked to from anywhere ... also with no explanation why. Also, a jpg is definitely not the correct format for that sort of document.

**Comment by Area63** [comment]
Sorry I thought you got my email for help on updating the district map. Can you help?

**Comment by MTecknology** [comment]
> Sorry I thought you got my email for help on updating the district map. Can you help?

If there was an email with any questions that I failed to respond to, I missed it. Even looking back through archives (and spam), I can't find anything. Can you provide a description of what you need help with?

-----

This entire website project is built around the [hugo](https://gohugo.io/) "static website generator," which has a lot of fantastic [documentation](https://gohugo.io/documentation/), including how to [test your own changes](https://gohugo.io/getting-started/usage/#build-your-site), [where files go](https://gohugo.io/getting-started/directory-structure/) and even [how to customize templates](https://gohugo.io/templates/).
 
The [aamod](https://github.com/recoverysource/aamod) project was built with the goal of providing a very stable and secure website solution with trivial/hands-free long-term maintenance. There was a lot of effort put into ensuring that maintaining meetings/events is as simple as copy/paste/tweak, but hugo is a powerful website generator and things can get confusing once you step outside of those areas.

All things considered, it seems like it might be best to close this PR and instead just [create an issue](https://github.com/area63aa/area63aa.org/issues) with a description of the changes you would like to see. I honestly believe you will have a much better experience if you limit your PRs to just meeting changes and use [issues](https://github.com/area63aa/area63aa.org/issues) for any other requests.

**Comment by MTecknology** [comment]
Closing in favor of #20.

**Pull request closed without merging**
