### PR TITLE
Update d2-sober-sunrise.yaml

### PR DESCRIPTION
**Pull request by Area63**
Update information for Sober Sunrise.

### CODE REVIEW

**Comment by MTecknology** [comment]
This does not appear to update zoom information.

**Comment by Area63** [comment]
> This does not appear to update zoom information.

The zoom information is not on the website. They would like it updated.

**Comment by MTecknology** [comment]
I have no idea what that means. Your description states you update zoom info, but zoom info is not updated. If they want it updated, then that change should be part of this PR.

**Comment by Area63** [comment]
https://github.com/area63aa/area63aa.org/commit/7f595fde0b2ce18c4b9249b95104b33c46049791
I have already updated the zoom information, but they submitted three more forms because the change was not on the website.

**Comment by MTecknology** [comment]
okay ... but that is a different pull request, why is /this/ pull request claiming to make that change?

**Comment by Area63** [comment]
It should be good to go.

**Pull request merged**
