### PR TITLE
Update and rename turning-point.yaml to d8-turning-point.yaml

### PR DESCRIPTION
**Pull request by Area63**
Update district number and address for Turning Point.

### CODE REVIEW

**Comment by MTecknology** [comment]
Why was EN removed without adding something else? Can you please start trying to provide a description?

**Comment by Area63** [comment]
> Why was EN removed without adding something else? Can you please start trying to provide a description?

On the meeting change form they did not select english. Should I add the English back?

**Comment by MTecknology** [comment]
> On the meeting change form they did not select english. Should I add the English back?

If you are not certain what the correct action is, then you should contact the user and make sure they wanted those tags removed. If they /do/ want the English tag removed, then they should specify an alternate language. Given the geographic area ... anything not EN would be worth a special note, don't you think?

**Comment by Area63** [comment]
> > On the meeting change form they did not select english. Should I add the English back?
> 
> If you are not certain what the correct action is, then you should contact the user and make sure they wanted those tags removed. If they /do/ want

Okay thanks for your help! I do think that it would be worth a special note if it is anything other than English.

**Pull request closed without merging**
