### PR TITLE
Update d5-bagladies.yaml

### PR DESCRIPTION
**Pull request by Area63**
Fix geo location and update note for Bag ladies meeting.

### CODE REVIEW

**Comment by MTecknology** [comment]
This can be merged once an actual description is provided. It would also be great if you put some effort into the change messages rather than using the defaults so that I don't have to create the descriptions while approving the change.

**Comment by Area63** [comment]
> This can be merged once an actual description is provided. It would also be great if you put some effort into the change messages rather than using the defaults so that I don't have to create the descriptions while approving the change.

Okay I will keep it in mind in my future change messages. I think I updated the desciption.

**Comment by MTecknology** [comment]
Try something like ... ``Fix geo location and update note for Bag Ladies meeting.``
Not every single change needs to be noted; things like the file name changing are quite arbitrary. They serve as an example, but it's left up to the editor to put meaningful text in that place; explaining why the change is actually important.

**Comment by Area63** [comment]
I understand, thanks!

**Pull request merged**
