### PR TITLE
create d2-sunday-evening-step-study.yaml

### PR DESCRIPTION
**Pull request by Area63**
https://github.com/area63aa/area63aa.org/compare/master...Area63:area63aa.org:patch-4#diff-7e778f7cd9e1b88bac108955c86b88489acc23d9393accc9cae7ace3ec6f279a

### CODE REVIEW

**Comment by MTecknology** [comment]
Can you please add "d2-" to the start of that filename? It's not "required," but helps a lot with organization. The current lack of this across the other files is actually due to a lack of data to fill it in with.

It's also not required to add geo coordinates, and my intention is a yearly cleanup, but since your username suggests you intend to contribute frequently, can you please also take the geo coordinates for this address from any of the other meetings held at this building?

Once those two changes are made, I'll be very happy to click merge on this. :)

**Comment by MTecknology** [comment]
Oh ... the checks failed because you have two "address:" lines and the second is formatted incorrectly. If you just delete that line, the build will succeed. (This is sort of a weird issue ... https://github.com/recoverysource/hugo-website/issues/1)

**Comment by Area63** [comment]
Thanks Mike Ill fix those things this morning!

**Comment by Area63** [comment]
I can just copy and paste the coordinates from the meetings at the same address.
Thanks for bearing with me as I learn some of the new things.

**Pull request merged**
